### ISSUE TITLE
Not detecting first stack of money

### ISSUE THREAD

**Issue by Kevin-Oudai** [Kevin-Oudai/Cooking-Fever-Bot#2]
The first stack of money to the far left is not being detected.

**Comment by Kevin-Oudai** [comment]
Solved this by clicking in the the locations money is expected. Did not solve the issue.

**Comment by phobosgmd** [comment]
Hi - this creates a new issue where after the level completes, the loop automatically detects money on the end screen, and clicks. the middle right click activates the question mark button above the piggy bank, in turn meaning the restart loop wont run. Im working on it right now
